# Generated by Django 5.0.6 on 2024-07-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
