# Generated by Django 5.0.6 on 2024-07-21 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True)),
                ('prenom', models.CharField(blank=True, max_length=5000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSermon', models.DateField()),
                ('theme', models.CharField(blank=True, max_length=5000, null=True)),
                ('subTheme', models.CharField(blank=True, max_length=5000, null=True)),
                ('bibleVerses', models.CharField(blank=True, max_length=5000, null=True)),
                ('link', models.CharField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sermons_images/')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('preacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preacher', to='sermons.preacher')),
            ],
        ),
    ]
